### ISSUE TITLE
Neo4j download location does not exist

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/oti#33]
The script ```setup_oti.sh```, if neo4j cannot be found, tries to dowload it from the address:

http://download.neo4j.org/artifact?edition=community&version=1.9.5&distribution=tarball&dlid=2600508

However, this does not seem to exist anymore.

**Comment by jar398** [comment]
Correct URL is in deploy/setup/install-neo4j-ap.sh in opentree repo.

**Comment by jar398** [comment]
Can I close this issue, @josephwb ?

**Comment by josephwb** [comment]
Checks out.
