### ISSUE TITLE
Problem with finding source trees - pg_2859 not found for Microtus californicus

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/oti#48]
From: Josef Uyeda

Hi,
I've been using the OpenTree APIs to find source trees for a set of ottids. Previously this seemed like it worked fine, but recently I've been obtaining a lot fewer hits for each taxon. It seems like the "/study/find_trees" api is missing hits that it should be finding. For example, if I search for the species "Microtus californicus" (ottid: 742231). I get:

$ curl -X POST http://api.opentreeoflife.org/v2/studies/find_trees \
-H "content-type:application/json" -d \
'{"property":"ot:ottId","value":"742231"}'
{
  "matched_studies" : [ ]
}

But I should at least get this tree: 
https://tree.opentreeoflife.org/curator/study/view/pg_2859/?tab=trees&tree=tree6643

If I search for just "Microtus", only pg_2171 and pg_2356 come up, both of which also contain Microtus californicus. It's not clear why some studies are still found with some ottids, while others are not.

https://groups.google.com/d/msg/opentreeoflife/KQwpLwtQBfs/h9JJoyMQFQAJ

**Comment by jar398** [comment]
I checked the indexing log and nothing seems amiss:

```Indexing study pg_2859 from http://api.opentreeoflife.org/phylesystem/v1/../default/v1/study/pg_2859.json
Calling "http://127.0.0.1:7478/db/data/ext/studies/graphdb/index_study" with data="{'url': 'http://api.opentreeoflife.org/phylesystem/v1/../default/v1/study/pg_2859.json'}"
OK```

**Comment by mtholder** [comment]
just noting https://github.com/OpenTreeOfLife/oti/issues/41 is a long-standing bug report about this search feature.

**Comment by jar398** [comment]
Duplicate of #41
